# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20160725_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
