# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_auto_20160925_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='stop_loss',
            field=models.FloatField(),
        ),
    ]
